### PR TITLE
Added Suggested Parameters

### PR DESCRIPTION
**Pull request by SteelCrusaders**
Added more definable parameters to be used.
Some cleanup to PS style guidelines

---
This change is [Reviewable](https://reviewable.io/reviews/iag-nz/xcertificate/1)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 62 \[r1\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KNe4anryJof0lkBs9hL:-KNe4anryJof0lkBs9hM:-1647233408) ([raw file](https://github.com/iag-nz/xcertificate/blob/7840beb1e78fa34499dcd3f10d8acee9582601dc/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L62)):*
> ```PowerShell
> 
>         [parameter(Mandatory = $false)]
>         [System.String]
> ```

Change to boolean.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 128 \[r1\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KNe8TrfdhFcsf70g098:-KNe8TrfdhFcsf70g099:1500553748) ([raw file](https://github.com/iag-nz/xcertificate/blob/7840beb1e78fa34499dcd3f10d8acee9582601dc/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L128)):*
> ```PowerShell
> KeySpec              = $KeySpec
> KeyLength            = $KeyLength
> Exportable           = $Exportable
> ```

```powershell
$($Exportable.ToString().ToUpper())
```

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 192 \[r1\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KNe8u84RMhccusr0BYB:-KNe8u84RMhccusr0BYC:-613871936) ([raw file](https://github.com/iag-nz/xcertificate/blob/7840beb1e78fa34499dcd3f10d8acee9582601dc/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L192)):*
> ```PowerShell
>     [OutputType([System.Boolean])]
>     param
>     (
> ```

Add parameters.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 246 \[r1\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KNe4h5coPMwoeSdRxOu:-KNe4h5coPMwoeSdRxOv:957614701) ([raw file](https://github.com/iag-nz/xcertificate/blob/7840beb1e78fa34499dcd3f10d8acee9582601dc/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L246)):*
> ```PowerShell
> 
> 
> Export-ModuleMember -Function *-TargetResource
> ```

Add CRLF

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/xcertificate/1)*

**Comment by SteelCrusaders** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 62 \[r1\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KNe4anryJof0lkBs9hL:-KNe9qrQKq-tdcP7Qi9e:-499146009) ([raw file](https://github.com/iag-nz/xcertificate/blob/7840beb1e78fa34499dcd3f10d8acee9582601dc/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L62)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Change to boolean.
</details>
Done.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 128 \[r1\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KNe8TrfdhFcsf70g098:-KNeCUxLwTclgd6fTimE:-499146009) ([raw file](https://github.com/iag-nz/xcertificate/blob/7840beb1e78fa34499dcd3f10d8acee9582601dc/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L128)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> ```powershell
> $($Exportable.ToString().ToUpper())
> ```
</details>
Done.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 192 \[r1\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KNe8u84RMhccusr0BYB:-KNeFhatMp-zWsUKJHyr:-499146009) ([raw file](https://github.com/iag-nz/xcertificate/blob/7840beb1e78fa34499dcd3f10d8acee9582601dc/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L192)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Add parameters.
</details>
Done.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 246 \[r1\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KNe4h5coPMwoeSdRxOu:-KNeLZ1ZFOn1yKDs5Rzg:-499146009) ([raw file](https://github.com/iag-nz/xcertificate/blob/7840beb1e78fa34499dcd3f10d8acee9582601dc/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L246)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Add CRLF
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/xcertificate/1)*

**Comment by PlagueHO** [comment]
Boom! @SteelCrusaders broke the build! :smile:

**Comment by PlagueHO** [comment]
Looking good @steelcrusaders - once you've comitted the updated tests/readme/examples, let me know and I'll review.

---

Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-:-KOlVyf1bH6uZImi79KS:b-xbz2bf)*

**Comment by SteelCrusaders** [comment]
@PlagueHO Ready for it to be demolised. :cry: 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-:-KOrWUGvDHDMCi5P7Rp6:byxyerx)*

**Comment by PlagueHO** [comment]
Looking pretty awesome @steelcrusaders  - good job. Just some minor style tweaks. Get those done and I'll merge then you can submit a PR to MSFT!

---

Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[ReadMe.md, line 90 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOriVfRtbRktt3dc0Va:-KOriVfRtbRktt3dc0Vb:baytnyp) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/ReadMe.md#L90)):*
> ```Markdown
>     - Renamed to match standard module name format (MSFT_x).
>     - Modified to meet 100 characters or less line length where possible.
>     - Split message and error strings into localization string files.
> ```

Add details of your change below this line.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 70 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOridt8Zmsc1w2FMSuR:-KOridt8Zmsc1w2FMSuS:b-12zafw) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L70)):*
> ```PowerShell
>         [System.String]
>         $KeyUsage = '0xa0',
>         
> ```

Recommend you enable automatic whitespace trimming in a tool like VS Code to automatically remove uneeded whitespace.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 112 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrl2FSTgQNeS99Gtl8:-KOrl2FSTgQNeS99Gtl9:b-z2nljo) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L112)):*
> ```PowerShell
>             CARootName           = $Cert.Issuer.split(',')[0].replace('CN=','')
>             KeyLength            = $Cert.Publickey.Key.KeySize
>             Exportable           = '' # This value can't be determined from the cert I think.
> ```

Remove  "I think"  :smile:

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 257 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrj9A9n6oVmIZTasro:-KOrj9A9n6oVmIZTasrp:bxe69k) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L257)):*
> ```PowerShell
>     {
>         $requestDetails += @"
> ```

Why you add blank line here? :smile:

---

*[Tests/Integration/MSFT_xCertReq.config.ps1, line 5 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrjgxH15vOGPMg8T5J:-KOrjgxH15vOGPMg8T5K:bjqp89l) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/Tests/Integration/MSFT_xCertReq.config.ps1#L5)):*
> ```PowerShell
> $CAServerFQDN = ([regex]::matches($CertUtilResult,'Server:[ \t]+`([A-Za-z0-9._-]+)''','IgnoreCase')).Groups[1].Value
> $CARootName = ([regex]::matches($CertUtilResult,'Name:[ \t]+`([\sA-Za-z0-9._-]+)''','IgnoreCase')).Groups[1].Value
> $KeyLength  = '4096'
> ```

Recommend we add all new parameters to this test even though they contain defaults.

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 240 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrkMHVRPWZJkvC4_Yn:-KOrkMHVRPWZJkvC4_Yo:bxrdpda) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/Tests/Unit/MSFT_xCertReq.tests.ps1#L240)):*
> ```PowerShell
> "@ 
>            
>         $CertInfKey = $CertInf -Replace 'KeyLength = ([0-z]*)', 'KeyLength = 4096' #Added 4:07pm
> ```

Remove comment please :smile:

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 243 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrkQ5V3AbI8841zDT5:-KOrkQ5V3AbI8841zDT6:b-97bxe8) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/Tests/Unit/MSFT_xCertReq.tests.ps1#L243)):*
> ```PowerShell
>         $CertInfRenew = $Certinf
>         $CertInfRenew += @"
> ```

Why extra line here?

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 246 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrkSIerqwfVyVNs2WR:-KOrkSIerqwfVyVNs2WS:b-q5zrh1) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/Tests/Unit/MSFT_xCertReq.tests.ps1#L246)):*
> ```PowerShell
> RenewalCert = $validThumbprint
> "@
>         $CertInfKeyRenew = $CertInfRenew -Replace 'KeyLength = ([0-z]*)', 'KeyLength = 4096' #Added 4:07pm
> ```

And this comment too :smile:

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 260 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrkXK-fBUTyZKErT7s:-KOrkXK-fBUTyZKErT7t:b-wq9rs1) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/Tests/Unit/MSFT_xCertReq.tests.ps1#L260)):*
> ```PowerShell
>                 $result.CAServerFQDN         | Should BeNullOrEmpty
>                 $result.CARootName           | Should BeExactly $CARootName
>                 $result.KeyLength            | Should BeNullOrEmpty # to change
> ```

No need for this comment right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-:-KOrlDt9WAqwYHGTKhv0:b-581xml)*

**Comment by SteelCrusaders** [comment]
Review status: 3 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 70 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOridt8Zmsc1w2FMSuR:-KOwR9WjP8Uw3z3Z9xfa:b-896fix) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L70)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Recommend you enable automatic whitespace trimming in a tool like VS Code to automatically remove uneeded whitespace.
</details>
Done.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 112 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrl2FSTgQNeS99Gtl8:-KOwRALr_N4iajlaqzDN:b-896fix) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L112)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Remove  "I think"  :smile:
</details>
Done.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 257 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrj9A9n6oVmIZTasro:-KOwOCof0LOXpa3hCsAy:b-sjx0ro) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L257)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Why you add blank line here? :smile:
</details>
The blank is not an accident! It was required as the request cert would be missing a newline and the request details would be inline with the OID Parameter

---

*[Tests/Integration/MSFT_xCertReq.config.ps1, line 5 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrjgxH15vOGPMg8T5J:-KOwTjOH9iB8Rkk9hp6M:b-m6tcdk) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/Tests/Integration/MSFT_xCertReq.config.ps1#L5)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Recommend we add all new parameters to this test even though they contain defaults.
</details>

Added!~

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 240 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrkMHVRPWZJkvC4_Yn:-KOwPOxIxOSxzyMZm4nS:b-896fja) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/Tests/Unit/MSFT_xCertReq.tests.ps1#L240)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Remove comment please :smile:
</details>
Done!

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 243 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrkQ5V3AbI8841zDT5:-KOwOtCIJIBRi19ArbdU:bi7t732) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/Tests/Unit/MSFT_xCertReq.tests.ps1#L243)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Why extra line here?
</details>
It was required as the request cert would be missing a newline and the request details would be inline with the OID Parameter.
E.g. (OID = 1.3.6.1.5.5.7.3.1RenewalCert = Thumbprint) <- Would cause an error i reckon

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 246 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrkSIerqwfVyVNs2WR:-KOwPRV7NJHh_X4qQuTt:b-896fix) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/Tests/Unit/MSFT_xCertReq.tests.ps1#L246)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> And this comment too :smile:
</details>
Done.

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 260 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrkXK-fBUTyZKErT7s:-KOwPmIVd4tSiwFqxNsB:b-c98utz) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/Tests/Unit/MSFT_xCertReq.tests.ps1#L260)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> No need for this comment right?
</details>
Nope! forgot to remove as a reminder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/xcertificate/1)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ReadMe.md, line 93 \[r5\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KP7GsUikBf9H0sYraEo:-KP7GsUj-PnZFv0BAl-T:b-f35eik) ([raw file](https://github.com/iag-nz/xcertificate/blob/435025bff03a7c7123d2dbe5fc55b9c512742ac8/ReadMe.md#L93)):*
> ```Markdown
> 
> ### 2.2.0.0
> * Added additional parameters to xCertReq 
> ```

Might be a good idea to list the parameters added.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 257 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrj9A9n6oVmIZTasro:-KP7H-gZ_x-qqYka9Ly2:b-96t1fe) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L257)):*
<details><summary><i>Previously, SteelCrusaders (Ashley Tok) wrote…</i></summary>
> The blank is not an accident! It was required as the request cert would be missing a newline and the request details would be inline with the OID Parameter
</details>
Oh cool! My bad!

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 243 \[r4\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KOrkQ5V3AbI8841zDT5:-KP7HSjWbRbjc79LuwpF:bs7apcl) ([raw file](https://github.com/iag-nz/xcertificate/blob/fcf61d794e93e5a739554b9e8a104f72bcc4ac78/Tests/Unit/MSFT_xCertReq.tests.ps1#L243)):*
<details><summary><i>Previously, SteelCrusaders (Ashley Tok) wrote…</i></summary>
> It was required as the request cert would be missing a newline and the request details would be inline with the OID Parameter.
> E.g. (OID = 1.3.6.1.5.5.7.3.1RenewalCert = Thumbprint) <- Would cause an error i reckon
</details>
Again - my bad :smile:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-:-KP7HcGJ5BxBuhB-_xti:bnfp4nl)*

**Comment by SteelCrusaders** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[ReadMe.md, line 93 \[r5\]](https://reviewable.io:443/reviews/iag-nz/xcertificate/1#-KP7GsUikBf9H0sYraEo:-KPA4gP6hwk0TptSCDFS:b-elbajp) ([raw file](https://github.com/iag-nz/xcertificate/blob/435025bff03a7c7123d2dbe5fc55b9c512742ac8/ReadMe.md#L93)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Might be a good idea to list the parameters added.
</details>
Done D:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/xcertificate/1)*

**Comment by PlagueHO** [comment]
@SteelCrusaders  - Ok, everything is looking good.

But sorry to be a pain, can we close this PR and can I get you to reissue it to this branch instead of the Dev branch (feature-25/new-xcertreq-parameters):
https://github.com/IAG-NZ/xCertificate/tree/feature-25/new-xcertreq-parameters

Otherwise your changes will automatically go into my existing PR to the PowerShell Org. We can then issue your PR from this new branch up to the PowerShell Org. Does that make sense?

**Comment by PlagueHO** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/iag-nz/xcertificate/1)*

**Pull request closed without merging**
